version: 2
before:
  hooks:
    - go mod download
    - go mod tidy
builds:
-
  id: openapi-mock-server-linux
  env:
    - CGO_ENABLED=0
  goos:
    - linux
  goarch:
    - amd64
    - arm64
  main: ./cmd/openapi-mock-server/main.go
  ldflags:
    - -s -w -X github.com/k2tzumi/openapi-mock-server.version={{.Version}} -X github.com/k2tzumi/openapi-mock-server.commit={{.FullCommit}} -X github.com/k2tzumi/openapi-mock-server.date={{.Date}} -X github.com/k2tzumi/openapi-mock-server/version.Version={{.Version}}
-
  id: openapi-mock-server-darwin
  env:
    - CGO_ENABLED=0
  goos:
    - darwin
  goarch:
    - amd64
    - arm64
  main: ./cmd/openapi-mock-server/main.go
  ldflags:
    - -s -w -X github.com/k2tzumi/openapi-mock-server.version={{.Version}} -X github.com/k2tzumi/openapi-mock-server.commit={{.FullCommit}} -X github.com/k2tzumi/openapi-mock-server.date={{.Date}} -X github.com/k2tzumi/openapi-mock-server/version.Version={{.Version}}
-
  id: openapi-mock-server-windows
  env:
    - CGO_ENABLED=0
  goos:
    - windows
  goarch:
    - amd64
  main: ./cmd/openapi-mock-server/main.go
  ldflags:
    - -s -w -X github.com/k2tzumi/openapi-mock-server.version={{.Version}} -X github.com/k2tzumi/openapi-mock-server.commit={{.FullCommit}} -X github.com/k2tzumi/openapi-mock-server.date={{.Date}} -X github.com/k2tzumi/openapi-mock-server/version.Version={{.Version}}
archives:
-
  id: openapi-mock-server-archive
  name_template: '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  format_overrides:
    - goos: darwin
      format: zip
  files:
    - LICENSE
    - CREDITS
    - README.md
    - CHANGELOG.md
-
  id: openapi-mock-server-binary
  name_template: '{{ .Binary }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  format: binary
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Version }}-next"
changelog:
nfpms:
  - id: openapi-mock-server-nfpms
    file_name_template: "{{ .ProjectName }}_{{ .Version }}-1_{{ .Arch }}"
    builds:
      - openapi-mock-server-linux
    homepage: https://github.com/k2tzumi/openapi-mock-server
    maintainer: Katsumi Kato <katzumi+github@gmail.com>
    description: openapi-mock-server is a command-line tool designed to run a mock API server based on an OpenAPI Specification.
    license: MIT
    formats:
      - apk
      - deb
      - rpm
    bindir: /usr/bin
    epoch: 1
release:
  draft: true
  replace_existing_draft: true
